### ISSUE TITLE
AttributeError: 'HTMLParser' object has no attribute 'unescape'

### ISSUE THREAD

**Issue by N0ury** [mvz/mdv#46]
Hello,
When running mdv I get the error:

```
Traceback (most recent call last):
  File "/home/nb/.local/bin/mdv", line 8, in <module>
    sys.exit(run())
  File "/home/nb/.local/lib/python3.9/site-packages/mdv/markdownviewer.py", line 1657, in run
    print(main(**kw) if PY3 else str(main(**kw)))
  File "/home/nb/.local/lib/python3.9/site-packages/mdv/markdownviewer.py", line 1375, in main
    the_html = MD.convert(md)
  File "/home/nb/.local/lib/python3.9/site-packages/markdown/core.py", line 268, in convert
    newRoot = treeprocessor.run(root)
  File "/home/nb/.local/lib/python3.9/site-packages/mdv/markdownviewer.py", line 1150, in run
    formatter(doc, out)
  File "/home/nb/.local/lib/python3.9/site-packages/mdv/markdownviewer.py", line 1145, in formatter
    formatter(c, out, hir + 1, parent=el)
  File "/home/nb/.local/lib/python3.9/site-packages/mdv/markdownviewer.py", line 970, in formatter
    t = html_parser.unescape(t)
AttributeError: 'HTMLParser' object has no attribute 'unescape'

```
I'm using Python  3.9.2 on Linux Debian.
mdv package has been installed via pip as it doesn't exists as Debian package.

Is this a bug or an installation issue?

**Comment by mvz** [comment]
Hi @N0ury, this is not the mdv you're looking for. Please re-post your issue here: https://github.com/axiros/terminal_markdown_viewer
